<?php

namespace app\models\repositories;

/**
 * CorporateImagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CorporateImagesRepository extends EntityRepository
{
}
