<?php

namespace app\models\repositories;

/**
 * EventsImagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventsImagesRepository extends EntityRepository
{
}
