<?php

namespace app\models\repositories;

/**
 * SeveralImagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeveralImagesRepository extends EntityRepository
{
}
