<?php

namespace app\models\repositories;

/**
 * TheatresImagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TheatresImagesRepository extends EntityRepository
{
}
