<?php

namespace app\models\repositories;

/**
 * UsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersRepository extends \app\models\repositories\EntityRepository
{
}
